# Generated by Django 3.0.8 on 2020-08-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('ENV', 'Envelope'), ('GTA', 'Gift Tag'), ('WBA', 'Wine Bag')], default='ENV', max_length=3),
        ),
    ]
