# Generated by Django 3.0.8 on 2020-08-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0005_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='images/products')),
                ('product_type', models.CharField(choices=[('ENV', 'Envelope'), ('GTA', 'Gift Tag'), ('WBA', 'Wine Bag')], default='ENV', max_length=3)),
            ],
        ),
    ]
