# Generated by Django 3.0.8 on 2020-08-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
